#include "apan_ai_selftest.h"

#include <stddef.h>
#include <stdint.h>

#define ODL_DISABLE_RAND_GENERATOR_ALPHA
#include "solistAi.h"
#include "ichiping_model.h"
#include "smpl_common.h"
#include "mcu.h"
#include "wdt.h"

#define AI_INSTANCE (0U)
#define AI_BUSY_LIMIT (65535UL)

static uint32_t last_predict_ticks;

static float bfloat16_to_float(bfloat16 value)
{
    union
    {
        uint32_t bits;
        float value;
    } converted;
    converted.bits = ((uint32_t)(uint16_t)value) << 16;
    return converted.value;
}

/* (Re)load the IchiPing model into accelerator instance 0.  Alpha is
   regenerated by the accelerator from seed/scaleAlpha (ODL_SetWeightAlpha is a
   stub in the library), so only Beta is transferred.  The collector app
   re-initializes the KX134 model after every request, so this is always
   called right before a prediction. */
void ApanAiSelfTestInitialize(void)
{
    ODL_Parameters parameters = {
        .inputSize = ICHI_MODEL_INPUT_SIZE,
        .hiddenSize = ICHI_MODEL_HIDDEN_SIZE,
        .outputSize = ICHI_MODEL_OUTPUT_SIZE,
        .forgettingFactor = (bfloat16)0x3F80,
        .activationFunction = ICHI_MODEL_ACTIVATION,
        .lossFunction = ICHI_MODEL_LOSS,
        .seed = ICHI_MODEL_SEED,
        .scaleAlpha = (bfloat16)ICHI_MODEL_SCALE_ALPHA_BF16,
        .scaleGamma = 0,
        .leakRate = 0
    };
    uint16_t row;

    smpl_enablePeripheral(AI_PERI);
    ODL_Initialize(AI_INSTANCE, &parameters);
    ODL_Reset(AI_INSTANCE);
    for (row = 0U; row < ICHI_MODEL_HIDDEN_SIZE; row++)
    {
        ODL_SetWeightBeta(&ichi_model_beta[row * ICHI_MODEL_OUTPUT_SIZE],
                          AI_INSTANCE,
                          (uint32_t)row * ICHI_MODEL_OUTPUT_SIZE * 2U,
                          ICHI_MODEL_OUTPUT_SIZE * 2U);
    }
}

uint8_t ApanAiSelfTestCaseCount(void)
{
    return (uint8_t)ICHI_MODEL_CASE_COUNT;
}

uint32_t ApanAiLastPredictTicks(void)
{
    return last_predict_ticks;
}

static bool predict(const bfloat16 *input, float output[APAN_AI_OUTPUT_COUNT],
                    uint8_t *class_id)
{
    bfloat16 raw_output[ICHI_MODEL_OUTPUT_SIZE];
    uint32_t busy_count = 0UL;
    uint32_t start;
    uint32_t end;
    uint8_t index;
    uint8_t best = 0U;

    ApanAiSelfTestInitialize();
    start = SysTick->VAL;
    ODL_StartPredict(AI_INSTANCE, (bfloat16 *)input, NULL);
    while (ODL_IsBusy() != 0UL)
    {
        if (++busy_count >= AI_BUSY_LIMIT)
        {
            return false;
        }
        wdt_clear();
    }
    end = SysTick->VAL;
    last_predict_ticks = (start >= end) ? (start - end) : (start + 0x01000000UL - end);
    ODL_GetResult(AI_INSTANCE, raw_output);
    for (index = 0U; index < ICHI_MODEL_OUTPUT_SIZE; index++)
    {
        output[index] = bfloat16_to_float(raw_output[index]);
        if ((index > 0U) && (output[index] > output[best]))
        {
            best = index;
        }
    }
    *class_id = best;
    return true;
}

bool ApanAiSelfTestRun(uint8_t case_id, float output[APAN_AI_OUTPUT_COUNT],
                       uint8_t *class_id)
{
    if ((output == NULL) || (class_id == NULL) ||
        (case_id >= ICHI_MODEL_CASE_COUNT) ||
        (ICHI_MODEL_OUTPUT_SIZE != APAN_AI_OUTPUT_COUNT) ||
        (ICHI_MODEL_INPUT_SIZE != APAN_AI_INPUT_COUNT))
    {
        return false;
    }
    return predict(ichi_model_cases[case_id], output, class_id);
}

bool ApanAiInfer(const int16_t input_bf16[APAN_AI_INPUT_COUNT],
                 float output[APAN_AI_OUTPUT_COUNT], uint8_t *class_id)
{
    if ((input_bf16 == NULL) || (output == NULL) || (class_id == NULL))
    {
        return false;
    }
    return predict((const bfloat16 *)input_bf16, output, class_id);
}
