"""工場の前段 (int8 CNN) はそのままに、ELM β をこのハード (Stamp-S3A) のセッションで解き直して実機用に書き出す。

sim/eval_stamp_mix.py の beta_stamp / beta_mix と同じ計算:
  stamp: β = (Σ_Stamp H^T H + λI)^-1 Σ_Stamp H^T Y
  mix  : UNO Q 学習 8 session を重み 1、Stamp を重み w = N_UNOQ / N_Stamp × --stamp-weight で加えた ridge
λ は与えたセッションの leave-one-session-out 平均 (32 クラス) で選ぶ。

出力:
  sim_export/solist_ds/board_model_frontend_32cls_stamp.npz   工場 npz の beta / ridge を差し替えたもの
  firmware/IchiPingInference/generated/ichiping_model.h      ichi_model_beta[] だけを差し替え (前段・自己テストはそのまま)
  firmware/IchiPingInference/generated/ichi_calib_prior.h    現地校正の P0 = w (G + λI)^-1 (G = 今回 β を解いた重み付き Gram)

usage: python sim/emit_stamp_beta.py stamp_20260926_s1_wav stamp_20260926_s2_wav ... [--mode stamp|mix] [--stamp-weight 1]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from eval_full_data import UNOQ_TRAIN, build_run  # noqa: E402
from emit_board_model import to_bf16_bits, c_array  # noqa: E402
from emit_frontend_model import ALPHA, ELM_HIDDEN, C, hard_sigmoid, mcu_reference  # noqa: E402
from eval_stamp_session import load_model, predict  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
MODEL = ROOT / "sim_export" / "solist_ds" / "board_model_frontend_32cls.npz"
OUT_NPZ = ROOT / "sim_export" / "solist_ds" / "board_model_frontend_32cls_stamp.npz"
GEN = ROOT / "firmware" / "IchiPingInference" / "generated"


def gram(Zs, ys, ws):
    G = np.zeros((ELM_HIDDEN, ELM_HIDDEN)); R = np.zeros((ELM_HIDDEN, C))
    for Z, y, w in zip(Zs, ys, ws):
        H = hard_sigmoid(Z @ ALPHA).astype(np.float64)
        Y = np.zeros((len(y), C)); Y[np.arange(len(y)), y] = 1
        G += w * H.T @ H; R += w * H.T @ Y
    return G, R


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("stamp", nargs="+")
    ap.add_argument("--mode", default="stamp", choices=("stamp", "mix"))
    ap.add_argument("--stamp-weight", type=float, default=1.0)
    ap.add_argument("--cal-per-state", type=int, default=5)
    a = ap.parse_args()
    z, qm, fq = load_model(MODEL)
    Z = {}
    Y = {}
    for r in a.stamp + (UNOQ_TRAIN if a.mode == "mix" else []):
        d = build_run(r)
        _, Z[r] = predict(d["X"].astype(np.float32), z, qm, fq)
        Y[r] = d["y"]
    n_u = sum(len(Y[r]) for r in UNOQ_TRAIN) if a.mode == "mix" else 0

    def fit(stamp_runs, lam):
        n_s = sum(len(Y[r]) for r in stamp_runs)
        w = n_u / n_s * a.stamp_weight if a.mode == "mix" else 1.0
        runs = stamp_runs + (UNOQ_TRAIN if a.mode == "mix" else [])
        ws = [w if r in stamp_runs else 1.0 for r in runs]
        G, R = gram([Z[r] for r in runs], [Y[r] for r in runs], ws)
        return np.linalg.solve(G + lam * np.eye(ELM_HIDDEN), R).astype(np.float32), G, n_s * w + n_u

    best = None
    for lam in (0.01, 0.1, 1.0, 10.0):
        accs = []
        for held in a.stamp if len(a.stamp) > 1 else []:
            beta, _, _ = fit([r for r in a.stamp if r != held], lam)
            accs.append(float(np.mean(mcu_reference(Z[held], beta).argmax(1) == Y[held])))
        acc = float(np.mean(accs)) if accs else 0.0
        print(f"  lambda {lam:5}: leave-one-session-out 32cls {acc:.3f}  {[round(x, 3) for x in accs]}")
        if best is None or acc > best[0]:
            best = (acc, lam)
    lam = best[1]
    beta, G, n_eff = fit(a.stamp, lam)
    for r in a.stamp:
        print(f"  {r}: train-fit 32cls {np.mean(mcu_reference(Z[r], beta).argmax(1) == Y[r]):.3f}")

    np.savez(OUT_NPZ, **{k: z[k] for k in z.files if k not in ("beta", "ridge")}, beta=beta, ridge=lam,
             stamp_runs=np.array(a.stamp), stamp_mode=a.mode, stamp_weight=a.stamp_weight)
    hp = GEN / "ichiping_model.h"
    h = hp.read_text(encoding="ascii")
    new = c_array("ichi_model_beta", to_bf16_bits(beta)).rstrip("\n")
    h, n = re.subn(r"static const int16_t ichi_model_beta\[1024\] = \{.*?\};", lambda m: new, h, flags=re.S)
    assert n == 1
    hp.write_text(h, encoding="ascii", newline="\n")

    # 現地校正の事前分布: 今回 β を解いた (重み付き) データの Gram に対して、校正 1 回分と等重みになる w
    n_cal = 32 * a.cal_per_state
    w = n_eff / n_cal
    p0 = w * np.linalg.inv(G + lam * np.eye(ELM_HIDDEN))
    emb = len(z["emb_mul"])
    out = ["/* Generated by sim/emit_stamp_beta.py (beta from Stamp-S3A sessions).  Do not edit. */",
           "#ifndef ICHI_CALIB_PRIOR_H", "#define ICHI_CALIB_PRIOR_H", "#include <stdint.h>", "",
           f"#define ICHI_CAL_PER_STATE {a.cal_per_state}",
           f"/* P0 = w (G + lambda I)^-1, w = {w:.3f}, lambda = {lam}; bf16, row-major {ELM_HIDDEN}x{ELM_HIDDEN}",
           f"   G over: {', '.join(a.stamp)}{' + UNO Q train' if a.mode == 'mix' else ''} */",
           c_array("ichi_calib_p0", to_bf16_bits(p0.astype(np.float32))), "",
           f"/* ELM alpha rows 0..{emb - 1} (the embedding inputs; the rest of the 167 inputs are zero),",
           "   Solist-AI Sim seed 1 = device alpha, bf16 row-major [input][hidden].  Lets the CPU",
           "   reproduce the factory head for a factory-vs-calibrated comparison. */",
           f"#define ICHI_CAL_ALPHA_ROWS {emb}",
           c_array("ichi_calib_alpha", to_bf16_bits(ALPHA[:emb].astype(np.float32))), "#endif"]
    (GEN / "ichi_calib_prior.h").write_text("\n".join(out) + "\n", encoding="ascii", newline="\n")
    print(f"mode={a.mode} lambda={lam} -> {OUT_NPZ.name}, {hp.name} (beta), ichi_calib_prior.h (P0 w={w:.1f})")


if __name__ == "__main__":
    main()
