"""On-site calibration prior for the Solist ELM head -> firmware/IchiPingInference/generated/ichi_calib_prior.h.

On-site calibration (docs/DEVELOPMENT.md: every state, one 6 s PRBS,
five 2 s windows with 1 s hop) retrains the ELM beta on the board (OS-ELM, forgetting
factor 1) while the AxlCORE keeps doing the inference.  Starting from the factory beta and
    P0 = w (G_f + lambda I)^-1,  G_f = H_f^T H_f over the factory training frames,
the sequential updates give exactly the batch "factory + calibration" solution
    beta = (G_f + w G_c + lambda I)^-1 (H_f^T Y_f + w H_c^T Y_c)
with the calibration set weighted w = N_factory / N_calibration x --weight-scale (1 = equal total
weight).  The update runs in float32 on the CPU (ichi_inference.c, P and beta kept in the
on-board FRAM): on the AxlCORE (ODL_StartTrain) beta and P are held in bf16, the rounding
piles up over the 160 updates and beta degrades or blows up (2026-09-26 board: every state
predicted as the first calibrated one; PC: bf16 OS-ELM 95-98% where float stays at 100%,
sim/eval_odl_calibration.py).  lambda = 10 keeps P0 well conditioned.

Uses the model in sim_export/solist_ds/board_model_frontend_32cls_best_s0.005.npz (emit_frontend_model.py,
or --model) and the same training runs (UNO Q session1-8, plus --stamp sessions).

usage: D:/GitHub/IchiPing/pc/.venv/Scripts/python.exe sim/emit_calibration_prior.py [--cal-per-state 5]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from emit_board_model import to_bf16_bits, hard_sigmoid, c_array  # noqa: E402
from emit_frontend_model import ALPHA, BLO, BHI, elm_input, int_forward  # noqa: E402
from eval_full_data import UNOQ_TRAIN, build_run  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
MODEL = ROOT / "sim_export" / "solist_ds" / "board_model_frontend_32cls_best_s0.005.npz"   # 完成版モデル
OUT = ROOT / "firmware" / "IchiPingInference" / "generated" / "ichi_calib_prior.h"


def f32_array(name, v, cols=6):
    flat = np.asarray(v, np.float32).reshape(-1)
    lines = ["    " + ", ".join(f"{float(x)!r}f" for x in flat[i:i + cols]) + "," for i in range(0, len(flat), cols)]
    return f"static const float {name}[{len(flat)}] = {{\n" + "\n".join(lines) + "\n};\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cal-per-state", type=int, default=5)
    ap.add_argument("--model", default=str(MODEL), help="前段+ELM の npz (emit_frontend_model.py の出力)")
    ap.add_argument("--stamp", nargs="*", default=[], help="そのモデルの学習に加えた Stamp セッション (G に含める)")
    ap.add_argument("--prior-ridge", type=float, default=10.0,
                    help="P0 の λ。β の ridge (0.1) のままだと G の小さい固有値方向で P0 が大きくなり、"
                         "AxlCORE の bf16 更新で β が発散する (2026-09-26 実機・PC で確認)")
    ap.add_argument("--weight-scale", type=float, default=1.0,
                    help="校正セットの重み w = N_factory / N_calibration × この値 (1 = 等重み)")
    a = ap.parse_args()
    z = np.load(a.model, allow_pickle=True)
    n_layers = sum(1 for k in z.files if k.endswith("_wq") and k.startswith("conv"))
    qm = [dict(wq=z[f"conv{i}_wq"], M=z[f"conv{i}_M"], B=z[f"conv{i}_B"], k=int(z[f"conv{i}_k"]),
               s=int(z[f"conv{i}_s"])) for i in range(n_layers)]
    fq = dict(wq=z["fc_wq"], M=z["fc_M"], B=z["fc_B"])
    mu, sd, s_in = z["in_mu"], z["in_sd"], float(z["s_in"])
    lam = a.prior_ridge

    X = np.concatenate([build_run(r)["X"].astype(np.float32) for r in UNOQ_TRAIN + a.stamp])
    xq = np.clip(np.round(((X[:, BLO:BHI] - mu) / sd) / s_in), -127, 127).astype(np.int8)
    E = np.concatenate([int_forward(xq[i:i + 2048], qm, fq) for i in range(0, len(xq), 2048)])
    H = hard_sigmoid(elm_input(E, z["emb_mul"], z["emb_add"]).astype(np.float64) @ ALPHA.astype(np.float64))
    n_cal = 32 * a.cal_per_state
    w = len(H) / n_cal * a.weight_scale
    p0 = w * np.linalg.inv(H.T @ H + lam * np.eye(H.shape[1]))
    print(f"factory frames {len(H)}, calibration samples {n_cal}, w = {w:.1f}, "
          f"P0 diag {np.diag(p0).min():.3e}..{np.diag(p0).max():.3e}")
    emb = len(z["emb_mul"])
    h = ["/* Generated by sim/emit_calibration_prior.py.  Do not edit. */",
         "#ifndef ICHI_CALIB_PRIOR_H", "#define ICHI_CALIB_PRIOR_H", "#include <stdint.h>", "",
         f"#define ICHI_CAL_PER_STATE {a.cal_per_state}",
         f"/* P0 = w (G_f + lambda I)^-1, w = {w:.3f}, lambda = {lam}; float32, row-major {p0.shape[0]}x{p0.shape[1]}",
         "   (the OS-ELM update runs in float32 on the CPU, ichi_inference.c) */",
         f32_array("ichi_calib_p0", p0), "",
         f"/* ELM alpha rows 0..{emb - 1} (the embedding inputs; the rest of the 167 inputs are zero),",
         "   Solist-AI Sim seed 1 = device alpha, bf16 row-major [input][hidden].  Lets the CPU",
         "   reproduce the factory head for a factory-vs-calibrated comparison. */",
         f"#define ICHI_CAL_ALPHA_ROWS {emb}",
         c_array("ichi_calib_alpha", to_bf16_bits(ALPHA[:emb].astype(np.float32))), "#endif"]
    OUT.write_text("\n".join(h) + "\n", encoding="ascii", newline="\n")
    print(f"-> {OUT}")


if __name__ == "__main__":
    main()
