"""make_solist_dataset.py の学習特徴から実機 (ML63Q2557 / AxlCORE-ODL) 用 14cls モデルを生成する。

- α: Solist-AI Sim seed=1 の実 α (sim_export/_alpha32_sim.npy, 167×32, |α|≤0.205)。
  実機では ODL_SetWeightAlpha は無効 (stub) で、seed=1・scaleAlpha=0x3E52 からアクセラレータが
  同じ α を再生成する (acrylic_pan の実機検証で一致確認済み)。
- β: (HᵀH + ridge·I)⁻¹ Hᵀ Y、H = hard_sigmoid((x·s)·α)。入力 x は標準化済 (mu/sd) で、
  実機へは (x·s) を bfloat16 化した 167 値を渡す。
- 出力:
  firmware/IchiPingInference/generated/ichiping_model.h : β (bf16), 自己テスト入力 (bf16), 期待クラス
  firmware/IchiPingInference/generated/golden_outputs.json : 自己テスト golden (PC bf16 参照計算)
  firmware/IchiPingInference/generated/stream_cases.npz     : 評価セット全 frame (bf16 入力, PC 出力)
  sim_export/solist_ds/board_model_<variant>.npz            : beta/mu/sd/s

usage: python sim/emit_board_model.py [--variant unoq_ir2] [--eval unoq_evening] [--scale 0.5]
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / "sim" / "_cache"
GEN = ROOT / "firmware" / "IchiPingInference" / "generated"
ALPHA = np.load(ROOT / "sim_export" / "_alpha32_sim.npy").astype(np.float32)   # (167,32)
D, M, C = 167, 32, 14
SCALE_ALPHA_BF16 = 0x3E52      # 0.205078125 (Sim seed=1 α の最大値と一致)
RIDGE = 0.1


def to_bf16_bits(v):
    raw = np.ascontiguousarray(np.asarray(v, np.float32)).view(np.uint32)
    return ((raw + np.uint32(0x7FFF) + ((raw >> 16) & 1)) >> 16).astype(np.uint16)


def from_bf16_bits(b):
    return (np.asarray(b, np.uint32) << 16).view(np.float32)


def q(v):
    return from_bf16_bits(to_bf16_bits(v))


def hard_sigmoid(z):
    return np.clip(0.2 * z + 0.5, 0.0, 1.0)


def mcu_reference(x_bf16_float, alpha, beta):
    """bf16 境界 + float32 累積の参照 (acrylic_pan dummy_model_pipeline.mcu_reference と同じ)。"""
    h = q(hard_sigmoid(x_bf16_float.astype(np.float32) @ q(alpha)))
    return q(h @ q(beta))


def c_array(name, bits, decl=None, cols=12):
    flat = np.asarray(bits).reshape(-1)
    lines = [f"    " + ", ".join(f"0x{int(v):04X}" for v in flat[i:i + cols]) + "," for i in range(0, len(flat), cols)]
    return f"static const int16_t {decl or f'{name}[{len(flat)}]'} = {{\n" + "\n".join(lines) + "\n};\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", default="unoq_ir2")
    ap.add_argument("--eval", default="unoq_evening")
    ap.add_argument("--scale", type=float, default=0.5)
    ap.add_argument("--frontend", default="none", choices=("none", "ridge"),
                    help="ridge: PC 学習の線形前段 (167→C スコア, z-score) を挟み、ELM 入力を C 次元にする")
    ap.add_argument("--ridge-lambda", type=float, default=10.0)
    ap.add_argument("--pad-to", type=int, default=0, help="ELM 入力をこの次元までゼロ埋めする (アクセラレータのブロック読み対策)")
    ap.add_argument("--probe", type=int, default=0, help="α プローブ用ファーム: 入力=この次元, β=単位行列, 出力=hidden")
    ap.add_argument("--hidden", type=int, default=32)
    ap.add_argument("--alpha-file", default="", help="実機プローブ α (.npz, key alpha) を使う。省略時は Sim 採取 α (167x32)")
    a = ap.parse_args()
    if a.probe:
        ni, m = a.probe, a.hidden
        beta = np.eye(m, dtype=np.float32)
        cases = np.zeros((1, ni), np.float32)
        hdr = f"""/* Generated by python sim/emit_board_model.py --probe {ni} --hidden {m}. Alpha probe: beta = identity. */
#ifndef ICHIPING_MODEL_H
#define ICHIPING_MODEL_H
#include <stdint.h>
#define ICHI_MODEL_INPUT_SIZE {ni}
#define ICHI_MODEL_HIDDEN_SIZE {m}
#define ICHI_MODEL_OUTPUT_SIZE {m}
#define ICHI_MODEL_CASE_COUNT 1
#define ICHI_MODEL_SEED 1
#define ICHI_MODEL_ACTIVATION 1
#define ICHI_MODEL_LOSS 1
#define ICHI_MODEL_SCALE_ALPHA_BF16 ((int16_t)0x{SCALE_ALPHA_BF16:04X})
"""
        hdr += c_array("ichi_model_beta", to_bf16_bits(beta))
        hdr += c_array("ichi_model_cases", to_bf16_bits(cases), decl="ichi_model_cases[ICHI_MODEL_CASE_COUNT][ICHI_MODEL_INPUT_SIZE]")
        hdr += "static const uint8_t ichi_model_case_class[ICHI_MODEL_CASE_COUNT] = {0};\n#endif\n"
        GEN.mkdir(parents=True, exist_ok=True)
        (GEN / "ichiping_model.h").write_text(hdr, encoding="ascii", newline="\n")
        print(f"probe header: input={ni} hidden={m} output={m} -> {GEN / 'ichiping_model.h'}")
        return
    global M
    M = a.hidden
    alpha_src = np.load(a.alpha_file)["alpha"].astype(np.float32) if a.alpha_file else ALPHA
    z = np.load(CACHE / f"solist_ds_{a.variant}.npz")
    mu, sd = z["mu"], z["sd"]
    fe = {}
    if a.frontend == "ridge":
        Xz = (z["X"] - mu) / sd
        Xa = np.hstack([Xz, np.ones((len(Xz), 1), np.float32)])
        Y0 = np.zeros((len(Xz), C)); Y0[np.arange(len(Xz)), z["y14"]] = 1.0
        W = np.linalg.solve(Xa.T @ Xa + a.ridge_lambda * np.eye(D + 1), Xa.T @ Y0).astype(np.float32)
        S = Xa @ W; ms, ss = S.mean(0), S.std(0) + 1e-6
        fe = dict(W=W, ms=ms, ss=ss)
        front = lambda Xr: ((np.hstack([(Xr - mu) / sd, np.ones((len(Xr), 1), np.float32)]) @ W) - ms) / ss
        Xn = (front(z["X"]) * a.scale).astype(np.float32)
        D_in = C
        if a.pad_to > D_in:
            padn = a.pad_to - D_in
            front_raw = front
            front = lambda Xr: np.hstack([front_raw(Xr), np.zeros((len(Xr), padn), np.float32)])
            Xn = np.hstack([Xn, np.zeros((len(Xn), padn), np.float32)]); D_in = a.pad_to
    else:
        Xn = (z["X"] - mu) / sd * a.scale
        D_in = D
    alpha = alpha_src[:D_in, :M]
    assert alpha.shape == (D_in, M), f"alpha shape {alpha.shape} != ({D_in},{M}); probe the device alpha for this (ni, m)"
    Y = np.zeros((len(Xn), C)); Y[np.arange(len(Xn)), z["y14"]] = 1.0
    H = hard_sigmoid(Xn @ alpha)
    live = np.abs(alpha).max(0) > 0            # プローブで α=0 の隠れユニット (実機で出力されない) は β から外す
    beta = np.zeros((M, C), np.float32)
    Hl = H[:, live]
    beta[live] = np.linalg.solve(Hl.T @ Hl + RIDGE * np.eye(int(live.sum())), Hl.T @ Y).astype(np.float32)
    if (~live).any():
        print(f"dead hidden units excluded from beta: {np.where(~live)[0].tolist()}")

    Xe = ((front(z[f"eval_{a.eval}_X"]) if a.frontend == "ridge" else (z[f"eval_{a.eval}_X"] - mu) / sd) * a.scale).astype(np.float32)
    ye = z[f"eval_{a.eval}_y14"]; ye32 = z[f"eval_{a.eval}_y32"]
    Xq = q(Xe)
    P_ref = mcu_reference(Xq, alpha, beta)                     # bf16 参照
    P_f32 = hard_sigmoid(Xe @ alpha) @ beta                    # float32 参照
    acc_ref = float((P_ref.argmax(1) == ye).mean()); acc_f32 = float((P_f32.argmax(1) == ye).mean())
    agree = float((P_ref.argmax(1) == P_f32.argmax(1)).mean())
    print(f"variant={a.variant} eval={a.eval} s={a.scale} frontend={a.frontend} D_in={D_in}: PC float32 acc={acc_f32:.1%}, bf16-ref acc={acc_ref:.1%}, "
          f"argmax agreement={agree:.1%}, max|Δscore|={np.abs(P_ref-P_f32).max():.4f}")

    # 自己テスト: クラスごとに最初の評価 frame
    case_idx = [int(np.flatnonzero(ye == c)[0]) for c in range(C)]
    cases = []
    for i, idx in enumerate(case_idx):
        cases.append(dict(board_case_id=i, case_id=f"{a.eval}_frame{idx}_class{int(ye[idx])}", eval_index=idx,
                          expected_class=int(ye[idx]), state32=int(ye32[idx]),
                          predicted_class=int(P_ref[idx].argmax()),
                          outputs=P_ref[idx].astype(float).tolist(),
                          outputs_float32=P_f32[idx].astype(float).tolist()))
    GEN.mkdir(parents=True, exist_ok=True)
    hdr = f"""/* Generated by python sim/emit_board_model.py --variant {a.variant} --eval {a.eval} --scale {a.scale} --frontend {a.frontend}. Do not edit. */
#ifndef ICHIPING_MODEL_H
#define ICHIPING_MODEL_H
#include <stdint.h>
#define ICHI_MODEL_INPUT_SIZE {D_in}
#define ICHI_MODEL_HIDDEN_SIZE {M}
#define ICHI_MODEL_OUTPUT_SIZE {C}
#define ICHI_MODEL_CASE_COUNT {C}
#define ICHI_MODEL_SEED 1
#define ICHI_MODEL_ACTIVATION 1
#define ICHI_MODEL_LOSS 1
#define ICHI_MODEL_SCALE_ALPHA_BF16 ((int16_t)0x{SCALE_ALPHA_BF16:04X})
"""
    hdr += c_array("ichi_model_beta", to_bf16_bits(beta))
    hdr += c_array("ichi_model_cases", to_bf16_bits(Xq[case_idx]),
                   decl="ichi_model_cases[ICHI_MODEL_CASE_COUNT][ICHI_MODEL_INPUT_SIZE]")
    hdr += "static const uint8_t ichi_model_case_class[ICHI_MODEL_CASE_COUNT] = {" + ", ".join(str(int(ye[i])) for i in case_idx) + "};\n"
    hdr += "#endif\n"
    (GEN / "ichiping_model.h").write_text(hdr, encoding="ascii", newline="\n")
    model_npz = ROOT / "sim_export" / "solist_ds" / f"board_model_{a.variant}_14cls.npz"
    np.savez(model_npz, beta=beta, beta_bf16=to_bf16_bits(beta), mu=mu, sd=sd, scale=a.scale, alpha=alpha, frontend=a.frontend, **fe)
    golden = dict(metadata=dict(model=f"ichiping_{a.variant}_{a.frontend}_{D_in}x{M}x{C}", variant=a.variant, eval_set=a.eval,
                                frontend=a.frontend, input_count=D_in, hidden_count=M, output_count=C, activation="hard_sigmoid", loss="mse",
                                scale_alpha_bf16=f"0x{SCALE_ALPHA_BF16:04X}", input_scale=a.scale, ridge=RIDGE,
                                pc_accuracy_float32=acc_f32, pc_accuracy_bf16_reference=acc_ref,
                                model_sha256=hashlib.sha256(model_npz.read_bytes()).hexdigest(),
                                alpha_origin=(a.alpha_file or "ROHM Solist-AI Simulator seed=1 capture (sim_export/_alpha32_sim.npy)")),
                  cases=cases)
    (GEN / "golden_outputs.json").write_text(json.dumps(golden, indent=1), encoding="utf-8")
    np.savez(GEN / "stream_cases.npz", inputs_bf16=to_bf16_bits(Xq), expected_class=ye, state32=ye32,
             outputs_ref=P_ref, outputs_f32=P_f32)
    print(f"header={GEN / 'ichiping_model.h'}  golden cases={len(cases)}  stream frames={len(Xq)}")


if __name__ == "__main__":
    main()
